import { prependOnceListener } from "process";
import React from "react";
import ReactDOM from "react-dom/client";

const Header = () => {
    return (
        <div className="header">
            <div className="logo-container">
                <img className="logo" src="https://imgs.search.brave.com/kZZ7hRCaR7W2BASjy_yIxMzyVU6JY9nzZRNyw5LNK2M/rs:fit:860:0:0/g:ce/aHR0cHM6Ly93d3cu/bG9nb2Rlc2lnbi5u/ZXQvbG9nby9zbW9r/aW5nLWJ1cmdlci13/aXRoLWxldHR1Y2Ut/MzYyNGxkLnBuZz9u/d209MSZud3M9MSZp/bmR1c3RyeT1mb29k/JnNmPSZ0eHRfa2V5/d29yZD1BbGw" alt="Logo" />
            </div>
            <div className="nav-items">
                <ul>
                    <li>Home</li>
                    <li>About Us</li>
                    <li>Contact</li>
                    <li>Cart</li>
                </ul>
            </div>
        </div>
    );
};

const RestaurantCard = (props) => {
    const {resData} = props;

    const {name,cuisines,avgRating,costForTwo,cloudinaryImageId,locality,areaName} = resData.info
    const {deliveryTime} = resData.info.sla
    return(
        <div className="res-card">
        <img className="food-img" alt="Paneer" src= {"https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/" +cloudinaryImageId}/>
        <h3>{name}</h3>
        <h4>{cuisines.join(", ")}</h4>
        <h4>{avgRating}</h4>
        <h4>{costForTwo}</h4>
        <h4>{deliveryTime} Minutes</h4>
        <h4>{locality}</h4>
        <h4>{areaName}</h4>
        </div>
    )
}

const resList = [
    {"info":{"id":"349817","name":"Pizza Hut","cloudinaryImageId":"2b4f62d606d1b2bfba9ba9e5386fabb7","locality":"Sector-79","areaName":"Omaxe World Street","costForTwo":"₹350 for two","cuisines":["Pizzas"],"avgRating":3.9,"parentId":"721","avgRatingString":"3.9","totalRatingsString":"1K+","sla":{"deliveryTime":44,"lastMileTravel":6.4,"serviceability":"SERVICEABLE","slaString":"40-45 mins","lastMileTravelString":"6.4 km","iconType":"ICON_TYPE_EMPTY"},"availability":{"nextCloseTime":"2024-05-08 01:00:00","opened":true},"badges":{},"isOpen":true,"type":"F","badgesV2":{"entityBadges":{"imageBased":{},"textBased":{},"textExtendedBadges":{}}},"aggregatedDiscountInfoV3":{"header":"50% OFF","subHeader":"UPTO ₹90"},"differentiatedUi":{"displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT","differentiatedUiMediaDetails":{"mediaType":"ADS_MEDIA_ENUM_IMAGE","lottie":{},"video":{}}},"reviewsSummary":{},"displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT","restaurantOfferPresentationInfo":{}},"analytics":{},"cta":{"link":"https://www.swiggy.com/restaurants/pizza-hut-sector-79-omaxe-world-street-faridabad-349817","type":"WEBLINK"}},

    {"info":{"id":"657322","name":"Chinese Wok","cloudinaryImageId":"e0839ff574213e6f35b3899ebf1fc597","locality":"Dussehra Ground","areaName":"PM Mall","costForTwo":"₹250 for two","cuisines":["Chinese","Asian","Tibetan","Desserts"],"avgRating":4.1,"parentId":"61955","avgRatingString":"4.1","totalRatingsString":"500+","sla":{"deliveryTime":42,"lastMileTravel":9.5,"serviceability":"SERVICEABLE","slaString":"40-45 mins","lastMileTravelString":"9.5 km","iconType":"ICON_TYPE_EMPTY"},"availability":{"nextCloseTime":"2024-05-08 00:00:00","opened":true},"badges":{"imageBadges":[{"imageId":"Rxawards/_CATEGORY-Chinese.png","description":"Delivery!"}]},"isOpen":true,"type":"F","badgesV2":{"entityBadges":{"imageBased":{"badgeObject":[{"attributes":{"description":"Delivery!","imageId":"Rxawards/_CATEGORY-Chinese.png"}}]},"textBased":{},"textExtendedBadges":{}}},"aggregatedDiscountInfoV3":{"header":"ITEMS","subHeader":"AT ₹179"},"differentiatedUi":{"displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT","differentiatedUiMediaDetails":{"mediaType":"ADS_MEDIA_ENUM_IMAGE","lottie":{},"video":{}}},"reviewsSummary":{},"displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT","restaurantOfferPresentationInfo":{}},"analytics":{},"cta":{"link":"https://www.swiggy.com/restaurants/chinese-wok-dussehra-ground-pm-mall-faridabad-657322","type":"WEBLINK"}},
    
    {"info":{"id":"89568","name":"UBQ by Barbeque Nation","cloudinaryImageId":"srupmcvgexew1ctmsgwo","locality":"EROS EF3 Mall","areaName":"Sector 20","costForTwo":"₹300 for two","cuisines":["North Indian","Barbecue","Biryani","Kebabs","Mughlai","Desserts"],"avgRating":3.9,"parentId":"10804","avgRatingString":"3.9","totalRatingsString":"1K+","sla":{"deliveryTime":54,"lastMileTravel":11.1,"serviceability":"SERVICEABLE","slaString":"50-55 mins","lastMileTravelString":"11.1 km","iconType":"ICON_TYPE_EMPTY"},"availability":{"nextCloseTime":"2024-05-07 16:30:00","opened":true},"badges":{},"isOpen":true,"type":"F","badgesV2":{"entityBadges":{"imageBased":{},"textBased":{},"textExtendedBadges":{}}},"aggregatedDiscountInfoV3":{"header":"₹125 OFF","subHeader":"ABOVE ₹599","discountTag":"FLAT DEAL"},"differentiatedUi":{"displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT","differentiatedUiMediaDetails":{"mediaType":"ADS_MEDIA_ENUM_IMAGE","lottie":{},"video":{}}},"reviewsSummary":{},"displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT","restaurantOfferPresentationInfo":{}},"analytics":{},"cta":{"link":"https://www.swiggy.com/restaurants/ubq-by-barbeque-nation-eros-ef3-mall-sector-20-faridabad-89568","type":"WEBLINK"}},
    
    {"info":{"id":"302693","name":"Barbeque Nation","cloudinaryImageId":"fmoykif0fxrlc2l8tdos","locality":"Sector 20","areaName":"Sector 20","costForTwo":"₹600 for two","cuisines":["North Indian","Barbecue","Biryani","Kebabs","Mughlai","Desserts"],"avgRating":3.8,"parentId":"2438","avgRatingString":"3.8","totalRatingsString":"500+","sla":{"deliveryTime":53,"lastMileTravel":11.1,"serviceability":"SERVICEABLE","slaString":"50-55 mins","lastMileTravelString":"11.1 km","iconType":"ICON_TYPE_EMPTY"},"availability":{"nextCloseTime":"2024-05-07 16:30:00","opened":true},"badges":{},"isOpen":true,"type":"F","badgesV2":{"entityBadges":{"imageBased":{},"textBased":{},"textExtendedBadges":{}}},"aggregatedDiscountInfoV3":{"header":"₹150 OFF","subHeader":"ABOVE ₹799","discountTag":"FLAT DEAL"},"differentiatedUi":{"displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT","differentiatedUiMediaDetails":{"mediaType":"ADS_MEDIA_ENUM_IMAGE","lottie":{},"video":{}}},"reviewsSummary":{},"displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT","restaurantOfferPresentationInfo":{}},"analytics":{},"cta":{"link":"https://www.swiggy.com/restaurants/barbeque-nation-sector-20-faridabad-302693","type":"WEBLINK"}},
    
    {"info":{"id":"64361","name":"Star Crust","cloudinaryImageId":"hgte5u6o5gvvluewdwet","locality":"Sector 10","areaName":"Sector 10","costForTwo":"₹200 for two","cuisines":["Pizzas","Chinese","Fast Food","Burgers","Italian-American","Beverages","Italian","Tandoor","Indian","Continental","Pastas"],"avgRating":4.2,"parentId":"15851","avgRatingString":"4.2","totalRatingsString":"10K+","sla":{"deliveryTime":30,"lastMileTravel":3,"serviceability":"SERVICEABLE","slaString":"25-30 mins","lastMileTravelString":"3.0 km","iconType":"ICON_TYPE_EMPTY"},"availability":{"nextCloseTime":"2024-05-07 21:45:00","opened":true},"badges":{"imageBadges":[{"imageId":"v1695133679/badges/Pure_Veg111.png","description":"pureveg"}]},"isOpen":true,"type":"F","badgesV2":{"entityBadges":{"imageBased":{"badgeObject":[{"attributes":{"description":"pureveg","imageId":"v1695133679/badges/Pure_Veg111.png"}}]},"textBased":{},"textExtendedBadges":{}}},"aggregatedDiscountInfoV3":{"header":"10% OFF","subHeader":"UPTO ₹80"},"differentiatedUi":{"displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT","differentiatedUiMediaDetails":{"mediaType":"ADS_MEDIA_ENUM_IMAGE","lottie":{},"video":{}}},"reviewsSummary":{},"displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT","restaurantOfferPresentationInfo":{}},"analytics":{},"cta":{"link":"https://www.swiggy.com/restaurants/star-crust-sector-10-faridabad-64361","type":"WEBLINK"}},
    
    {"info":{"id":"356223","name":"KFC","cloudinaryImageId":"RX_THUMBNAIL/IMAGES/VENDOR/2024/4/17/1a170357-6a8a-4f7e-a1ca-18f56d041eb5_356223.JPG","locality":"Sector-79","areaName":"Omaxe World Street","costForTwo":"₹450 for two","cuisines":["Burgers","Biryani","American","Snacks","Fast Food"],"avgRating":4.3,"parentId":"547","avgRatingString":"4.3","totalRatingsString":"1K+","sla":{"deliveryTime":35,"lastMileTravel":6.2,"serviceability":"SERVICEABLE","slaString":"30-35 mins","lastMileTravelString":"6.2 km","iconType":"ICON_TYPE_EMPTY"},"availability":{"nextCloseTime":"2024-05-08 02:00:00","opened":true},"badges":{"imageBadges":[{"imageId":"Rxawards/_CATEGORY-Burger.png","description":"Delivery!"}]},"isOpen":true,"type":"F","badgesV2":{"entityBadges":{"imageBased":{"badgeObject":[{"attributes":{"description":"Delivery!","imageId":"Rxawards/_CATEGORY-Burger.png"}}]},"textBased":{},"textExtendedBadges":{}}},"aggregatedDiscountInfoV3":{"header":"20% OFF","subHeader":"UPTO ₹50"},"differentiatedUi":{"displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT","differentiatedUiMediaDetails":{"mediaType":"ADS_MEDIA_ENUM_IMAGE","lottie":{},"video":{}}},"reviewsSummary":{},"displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT","restaurantOfferPresentationInfo":{}},"analytics":{},"cta":{"link":"https://www.swiggy.com/restaurants/kfc-sector-79-omaxe-world-street-faridabad-356223","type":"WEBLINK"}},
    
    {"info":{"id":"580243","name":"Natural Ice Cream","cloudinaryImageId":"zjrdoxtmeig9krgcb7yt","locality":"Omaxe World Street","areaName":"Bhataula Village","costForTwo":"₹150 for two","cuisines":["Ice Cream","Desserts"],"avgRating":4.7,"veg":true,"parentId":"2093","avgRatingString":"4.7","totalRatingsString":"100+","sla":{"deliveryTime":32,"lastMileTravel":6.3,"serviceability":"SERVICEABLE","slaString":"30-35 mins","lastMileTravelString":"6.3 km","iconType":"ICON_TYPE_EMPTY"},"availability":{"nextCloseTime":"2024-05-07 23:30:00","opened":true},"badges":{"imageBadges":[{"imageId":"v1695133679/badges/Pure_Veg111.png","description":"pureveg"}]},"isOpen":true,"type":"F","badgesV2":{"entityBadges":{"imageBased":{"badgeObject":[{"attributes":{"description":"pureveg","imageId":"v1695133679/badges/Pure_Veg111.png"}}]},"textBased":{},"textExtendedBadges":{}}},"aggregatedDiscountInfoV3":{"header":"50% OFF","subHeader":"UPTO ₹100"},"differentiatedUi":{"displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT","differentiatedUiMediaDetails":{"mediaType":"ADS_MEDIA_ENUM_IMAGE","lottie":{},"video":{}}},"reviewsSummary":{},"displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT","restaurantOfferPresentationInfo":{}},"analytics":{},"cta":{"link":"https://www.swiggy.com/restaurants/natural-ice-cream-omaxe-world-street-bhataula-village-faridabad-580243","type":"WEBLINK"}},
    
    {"info":{"id":"618662","name":"Grameen Kulfi","cloudinaryImageId":"wdisrht52lajevzznzcg","locality":"Huda Market","areaName":"Sector 7","costForTwo":"₹120 for two","cuisines":["Ice Cream","Desserts"],"avgRating":4.8,"veg":true,"parentId":"12175","avgRatingString":"4.8","totalRatingsString":"50+","sla":{"deliveryTime":30,"lastMileTravel":3,"serviceability":"SERVICEABLE","slaString":"30-35 mins","lastMileTravelString":"3.0 km","iconType":"ICON_TYPE_EMPTY"},"availability":{"nextCloseTime":"2024-05-07 23:00:00","opened":true},"badges":{"imageBadges":[{"imageId":"v1695133679/badges/Pure_Veg111.png","description":"pureveg"}]},"isOpen":true,"type":"F","badgesV2":{"entityBadges":{"imageBased":{"badgeObject":[{"attributes":{"description":"pureveg","imageId":"v1695133679/badges/Pure_Veg111.png"}}]},"textBased":{},"textExtendedBadges":{}}},"aggregatedDiscountInfoV3":{"header":"50% OFF","subHeader":"UPTO ₹100"},"differentiatedUi":{"displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT","differentiatedUiMediaDetails":{"mediaType":"ADS_MEDIA_ENUM_IMAGE","lottie":{},"video":{}}},"reviewsSummary":{},"displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT","restaurantOfferPresentationInfo":{}},"analytics":{},"cta":{"link":"https://www.swiggy.com/restaurants/grameen-kulfi-huda-market-sector-7-faridabad-618662","type":"WEBLINK"}},
    
    {"info":{"id":"762359","name":"Yummo Ice Creams","cloudinaryImageId":"8a89cc36168fb9974b37aaf5a5f6be2e","locality":"Sector 7","areaName":"PNB Bank","costForTwo":"₹120 for two","cuisines":["Ice Cream","Desserts"],"avgRating":4.5,"veg":true,"parentId":"449734","avgRatingString":"4.5","totalRatingsString":"10+","sla":{"deliveryTime":25,"lastMileTravel":3,"serviceability":"SERVICEABLE","slaString":"20-25 mins","lastMileTravelString":"3.0 km","iconType":"ICON_TYPE_EMPTY"},"availability":{"nextCloseTime":"2024-05-07 23:00:00","opened":true},"badges":{"imageBadges":[{"imageId":"v1695133679/badges/Pure_Veg111.png","description":"pureveg"}]},"isOpen":true,"type":"F","badgesV2":{"entityBadges":{"imageBased":{"badgeObject":[{"attributes":{"description":"pureveg","imageId":"v1695133679/badges/Pure_Veg111.png"}}]},"textBased":{},"textExtendedBadges":{}}},"aggregatedDiscountInfoV3":{"header":"50% OFF","subHeader":"UPTO ₹100"},"differentiatedUi":{"displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT","differentiatedUiMediaDetails":{"mediaType":"ADS_MEDIA_ENUM_IMAGE","lottie":{},"video":{}}},"reviewsSummary":{},"displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT","isNewlyOnboarded":true,"restaurantOfferPresentationInfo":{}},"analytics":{},"cta":{"link":"https://www.swiggy.com/restaurants/yummo-ice-creams-sector-7-pnb-bank-faridabad-762359","type":"WEBLINK"}},
    
    {"info":{"id":"537371","name":"Baskin Robbins - Ice Cream Desserts","cloudinaryImageId":"85ccae4e3576f9330af102c46ca85395","locality":"Omaxe World Street","areaName":"Sector 81","costForTwo":"₹250 for two","cuisines":["Desserts","Ice Cream"],"avgRating":4.2,"veg":true,"parentId":"5588","avgRatingString":"4.2","totalRatingsString":"50+","sla":{"deliveryTime":35,"lastMileTravel":6.2,"serviceability":"SERVICEABLE","slaString":"35-40 mins","lastMileTravelString":"6.2 km","iconType":"ICON_TYPE_EMPTY"},"availability":{"nextCloseTime":"2024-05-07 23:30:00","opened":true},"badges":{},"isOpen":true,"type":"F","badgesV2":{"entityBadges":{"imageBased":{},"textBased":{},"textExtendedBadges":{}}},"aggregatedDiscountInfoV3":{"header":"50% OFF","subHeader":"UPTO ₹90"},"differentiatedUi":{"displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT","differentiatedUiMediaDetails":{"mediaType":"ADS_MEDIA_ENUM_IMAGE","lottie":{},"video":{}}},"reviewsSummary":{},"displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT","restaurantOfferPresentationInfo":{}},"analytics":{},"cta":{"link":"https://www.swiggy.com/restaurants/baskin-robbins-ice-cream-desserts-omaxe-world-street-sector-81-faridabad-537371","type":"WEBLINK"}},

    {"info":{"id":"207998","name":"Burger King","cloudinaryImageId":"e33e1d3ba7d6b2bb0d45e1001b731fcf","locality":"Eldeco Station 1 Mall","areaName":"Sector 12","costForTwo":"₹350 for two","cuisines":["Burgers","American"],"avgRating":4.2,"parentId":"166","avgRatingString":"4.2","totalRatingsString":"10K+","sla":{"deliveryTime":43,"lastMileTravel":7,"serviceability":"SERVICEABLE","slaString":"40-45 mins","lastMileTravelString":"7.0 km","iconType":"ICON_TYPE_EMPTY"},"availability":{"nextCloseTime":"2024-05-08 05:00:00","opened":true},"badges":{},"isOpen":true,"type":"F","badgesV2":{"entityBadges":{"imageBased":{},"textBased":{},"textExtendedBadges":{}}},"aggregatedDiscountInfoV3":{"header":"50% OFF","subHeader":"UPTO ₹90"},"differentiatedUi":{"displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT","differentiatedUiMediaDetails":{"mediaType":"ADS_MEDIA_ENUM_IMAGE","lottie":{},"video":{}}},"reviewsSummary":{},"displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT","restaurantOfferPresentationInfo":{}},"analytics":{},"cta":{"link":"https://www.swiggy.com/restaurants/burger-king-eldeco-station-1-mall-sector-12-faridabad-207998","type":"WEBLINK"}},

    {"info":{"id":"657323","name":"Big Bowl","cloudinaryImageId":"c99751d54e4e1847186c62b3309c1327","locality":"Piyush Mahendra Metropolitan Mall","areaName":"Narela Rajeev Nagar","costForTwo":"₹250 for two","cuisines":["Chinese","Tibetan","Desserts"],"avgRating":4.2,"parentId":"434792","avgRatingString":"4.2","totalRatingsString":"100+","sla":{"deliveryTime":43,"lastMileTravel":9.5,"serviceability":"SERVICEABLE","slaString":"40-45 mins","lastMileTravelString":"9.5 km","iconType":"ICON_TYPE_EMPTY"},"availability":{"nextCloseTime":"2024-05-08 00:00:00","opened":true},"badges":{},"isOpen":true,"type":"F","badgesV2":{"entityBadges":{"imageBased":{},"textBased":{},"textExtendedBadges":{}}},"aggregatedDiscountInfoV3":{"header":"ITEMS","subHeader":"AT ₹179"},"differentiatedUi":{"displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT","differentiatedUiMediaDetails":{"mediaType":"ADS_MEDIA_ENUM_IMAGE","lottie":{},"video":{}}},"reviewsSummary":{},"displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT","restaurantOfferPresentationInfo":{}},"analytics":{},"cta":{"link":"https://www.swiggy.com/restaurants/big-bowl-piyush-mahendra-metropolitan-mall-narela-rajeev-nagar-faridabad-657323","type":"WEBLINK"}},
    
    {"info":{"id":"336062","name":"Wendy's Burgers","cloudinaryImageId":"f1aa621021a2826088089b89842d4e7c","locality":"Nehru Ground","areaName":"New Industrial Township","costForTwo":"₹200 for two","cuisines":["Burgers","American","Fast Food","Snacks","Beverages"],"avgRating":4.3,"parentId":"972","avgRatingString":"4.3","totalRatingsString":"1K+","sla":{"deliveryTime":50,"lastMileTravel":8.7,"serviceability":"SERVICEABLE","slaString":"50-55 mins","lastMileTravelString":"8.7 km","iconType":"ICON_TYPE_EMPTY"},"availability":{"nextCloseTime":"2024-05-07 23:59:00","opened":true},"badges":{"textExtendedBadges":[{"iconId":"guiltfree/GF_Logo_android_3x","shortDescription":"options available","fontColor":"#7E808C"}]},"isOpen":true,"type":"F","badgesV2":{"entityBadges":{"imageBased":{},"textBased":{},"textExtendedBadges":{"badgeObject":[{"attributes":{"description":"","fontColor":"#7E808C","iconId":"guiltfree/GF_Logo_android_3x","shortDescription":"options available"}}]}}},"aggregatedDiscountInfoV3":{"header":"ITEMS","subHeader":"AT ₹149"},"differentiatedUi":{"displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT","differentiatedUiMediaDetails":{"mediaType":"ADS_MEDIA_ENUM_IMAGE","lottie":{},"video":{}}},"reviewsSummary":{},"displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT","restaurantOfferPresentationInfo":{}},"analytics":{},"cta":{"link":"https://www.swiggy.com/restaurants/wendys-burgers-nehru-ground-new-industrial-township-faridabad-336062","type":"WEBLINK"}},
    
    {"info":{"id":"21986","name":"Dark Brown","cloudinaryImageId":"mzdetw2s1ihmpiegkhyl","locality":"Shopping Centre Market","areaName":"Sector 15","costForTwo":"₹250 for two","cuisines":["Italian-American","Continental","Burgers","Pizzas","Pastas","Chinese","Beverages","Salads","Asian","Healthy Food","Fast Food","Chaat","Snacks","Desserts","American","Italian","Momos","Rolls & Wraps","Cafe"],"avgRating":4.3,"parentId":"16162","avgRatingString":"4.3","totalRatingsString":"10K+","sla":{"deliveryTime":46,"lastMileTravel":7.3,"serviceability":"SERVICEABLE","slaString":"45-50 mins","lastMileTravelString":"7.3 km","iconType":"ICON_TYPE_EMPTY"},"availability":{"nextCloseTime":"2024-05-08 00:00:00","opened":true},"badges":{},"isOpen":true,"type":"F","badgesV2":{"entityBadges":{"imageBased":{},"textBased":{},"textExtendedBadges":{}}},"aggregatedDiscountInfoV3":{"header":"₹125 OFF","subHeader":"ABOVE ₹199","discountTag":"FLAT DEAL"},"differentiatedUi":{"displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT","differentiatedUiMediaDetails":{"mediaType":"ADS_MEDIA_ENUM_IMAGE","lottie":{},"video":{}}},"reviewsSummary":{},"displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT","restaurantOfferPresentationInfo":{}},"analytics":{},"cta":{"link":"https://www.swiggy.com/restaurants/dark-brown-shopping-centre-market-sector-15-faridabad-21986","type":"WEBLINK"}},
    
    {"info":{"id":"253728","name":"McDonald's","cloudinaryImageId":"535fc9f9c135f7982317bbb6a64a1ffc","locality":"Crown Plaza Mall","areaName":"Sector 15","costForTwo":"₹400 for two","cuisines":["American"],"avgRating":4.3,"parentId":"630","avgRatingString":"4.3","totalRatingsString":"10K+","sla":{"deliveryTime":53,"lastMileTravel":8.3,"serviceability":"SERVICEABLE","slaString":"50-55 mins","lastMileTravelString":"8.3 km","iconType":"ICON_TYPE_EMPTY"},"availability":{"nextCloseTime":"2024-05-08 00:15:00","opened":true},"badges":{"imageBadges":[{"imageId":"Rxawards/_CATEGORY-Burger.png","description":"Delivery!"}]},"isOpen":true,"type":"F","badgesV2":{"entityBadges":{"imageBased":{"badgeObject":[{"attributes":{"description":"Delivery!","imageId":"Rxawards/_CATEGORY-Burger.png"}}]},"textBased":{},"textExtendedBadges":{}}},"aggregatedDiscountInfoV3":{"header":"20% OFF","subHeader":"UPTO ₹50"},"differentiatedUi":{"displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT","differentiatedUiMediaDetails":{"mediaType":"ADS_MEDIA_ENUM_IMAGE","lottie":{},"video":{}}},"reviewsSummary":{},"displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT","restaurantOfferPresentationInfo":{}},"analytics":{},"cta":{"link":"https://www.swiggy.com/restaurants/mcdonalds-crown-plaza-mall-sector-15-faridabad-253728","type":"WEBLINK"}},
    
    {"info":{"id":"28755","name":"ABC Biryani Wala","cloudinaryImageId":"pdtdjeece6pgbmjq5mft","locality":"Bk Chowk","areaName":"New Industrial Township","costForTwo":"₹200 for two","cuisines":["Biryani"],"avgRating":4.1,"parentId":"16108","avgRatingString":"4.1","totalRatingsString":"10K+","sla":{"deliveryTime":44,"lastMileTravel":8.7,"serviceability":"SERVICEABLE","slaString":"40-45 mins","lastMileTravelString":"8.7 km","iconType":"ICON_TYPE_EMPTY"},"availability":{"nextCloseTime":"2024-05-07 18:00:00","opened":true},"badges":{},"isOpen":true,"type":"F","badgesV2":{"entityBadges":{"imageBased":{},"textBased":{},"textExtendedBadges":{}}},"aggregatedDiscountInfoV3":{"header":"30% OFF","subHeader":"UPTO ₹75"},"differentiatedUi":{"displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT","differentiatedUiMediaDetails":{"mediaType":"ADS_MEDIA_ENUM_IMAGE","lottie":{},"video":{}}},"reviewsSummary":{},"displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT","restaurantOfferPresentationInfo":{}},"analytics":{},"cta":{"link":"https://www.swiggy.com/restaurants/abc-biryani-wala-bk-chowk-new-industrial-township-faridabad-28755","type":"WEBLINK"}},
    
    {"info":{"id":"325188","name":"Kwality Walls Frozen Dessert and Ice Cream Shop","cloudinaryImageId":"kpalaprbfuscsnuvzthi","locality":"Block C","areaName":"New Industrial Township 1","costForTwo":"₹300 for two","cuisines":["Desserts","Ice Cream","Ice Cream Cakes"],"avgRating":4.6,"veg":true,"parentId":"582","avgRatingString":"4.6","totalRatingsString":"1K+","sla":{"deliveryTime":39,"lastMileTravel":7.8,"serviceability":"SERVICEABLE","slaString":"35-40 mins","lastMileTravelString":"7.8 km","iconType":"ICON_TYPE_EMPTY"},"availability":{"nextCloseTime":"2024-05-07 23:55:00","opened":true},"badges":{},"isOpen":true,"type":"F","badgesV2":{"entityBadges":{"imageBased":{},"textBased":{},"textExtendedBadges":{}}},"aggregatedDiscountInfoV3":{"header":"50% OFF","subHeader":"UPTO ₹90"},"differentiatedUi":{"displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT","differentiatedUiMediaDetails":{"mediaType":"ADS_MEDIA_ENUM_IMAGE","lottie":{},"video":{}}},"reviewsSummary":{},"displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT","restaurantOfferPresentationInfo":{}},"analytics":{},"cta":{"link":"https://www.swiggy.com/restaurants/kwality-walls-frozen-dessert-and-ice-cream-shop-block-c-new-industrial-township-1-faridabad-325188","type":"WEBLINK"}},
    
    {"info":{"id":"468366","name":"Subway","cloudinaryImageId":"63178e3e64d503a479f2a2048a474552","locality":"Omaxe World Street","areaName":"Sector 16_FBD","costForTwo":"₹300 for two","cuisines":["Continental","Fast Food","Healthy Food","Salads","Desserts","Beverages"],"avgRating":4,"parentId":"2","avgRatingString":"4.0","totalRatingsString":"1K+","sla":{"deliveryTime":47,"lastMileTravel":6.3,"serviceability":"SERVICEABLE","slaString":"45-50 mins","lastMileTravelString":"6.3 km","iconType":"ICON_TYPE_EMPTY"},"availability":{"nextCloseTime":"2024-05-07 23:55:00","opened":true},"badges":{},"isOpen":true,"aggregatedDiscountInfoV2":{},"type":"F","badgesV2":{"entityBadges":{"imageBased":{},"textBased":{},"textExtendedBadges":{}}},"differentiatedUi":{"displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT","differentiatedUiMediaDetails":{"mediaType":"ADS_MEDIA_ENUM_IMAGE","lottie":{},"video":{}}},"reviewsSummary":{},"displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT","restaurantOfferPresentationInfo":{}},"analytics":{},"cta":{"link":"https://www.swiggy.com/restaurants/subway-omaxe-world-street-sector-16-fbd-faridabad-468366","type":"WEBLINK"}},
    
    {"info":{"id":"242347","name":"Faasos - Wraps, Rolls & Shawarma","cloudinaryImageId":"af33b81798b11deba338e94b7585d348","locality":"Nehru Ground","areaName":"New Industrial Township","costForTwo":"₹200 for two","cuisines":["Kebabs","Fast Food","Snacks","American","Healthy Food","Desserts","Beverages"],"avgRating":4.1,"parentId":"21809","avgRatingString":"4.1","totalRatingsString":"1K+","sla":{"deliveryTime":52,"lastMileTravel":8.7,"serviceability":"SERVICEABLE","slaString":"50-55 mins","lastMileTravelString":"8.7 km","iconType":"ICON_TYPE_EMPTY"},"availability":{"nextCloseTime":"2024-05-07 23:59:00","opened":true},"badges":{"textExtendedBadges":[{"iconId":"guiltfree/GF_Logo_android_3x","shortDescription":"options available","fontColor":"#7E808C"}]},"isOpen":true,"type":"F","badgesV2":{"entityBadges":{"imageBased":{},"textBased":{},"textExtendedBadges":{"badgeObject":[{"attributes":{"description":"","fontColor":"#7E808C","iconId":"guiltfree/GF_Logo_android_3x","shortDescription":"options available"}}]}}},"aggregatedDiscountInfoV3":{"header":"₹125 OFF","subHeader":"ABOVE ₹199","discountTag":"FLAT DEAL"},"differentiatedUi":{"displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT","differentiatedUiMediaDetails":{"mediaType":"ADS_MEDIA_ENUM_IMAGE","lottie":{},"video":{}}},"reviewsSummary":{},"displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT","restaurantOfferPresentationInfo":{}},"analytics":{},"cta":{"link":"https://www.swiggy.com/restaurants/faasos-wraps-rolls-and-shawarma-nehru-ground-new-industrial-township-faridabad-242347","type":"WEBLINK"}},
    
    {"info":{"id":"242354","name":"LunchBox - Meals and Thalis","cloudinaryImageId":"4edcfc66d91018d69894941ebb3c8d16","locality":"Rani Bhawan","areaName":"NIT","costForTwo":"₹200 for two","cuisines":["Biryani","North Indian","Punjabi","Healthy Food","Desserts","Beverages"],"avgRating":4.2,"parentId":"4925","avgRatingString":"4.2","totalRatingsString":"1K+","sla":{"deliveryTime":53,"lastMileTravel":8.7,"serviceability":"SERVICEABLE","slaString":"50-55 mins","lastMileTravelString":"8.7 km","iconType":"ICON_TYPE_EMPTY"},"availability":{"nextCloseTime":"2024-05-07 23:59:00","opened":true},"badges":{"textExtendedBadges":[{"iconId":"guiltfree/GF_Logo_android_3x","shortDescription":"options available","fontColor":"#7E808C"}]},"isOpen":true,"type":"F","badgesV2":{"entityBadges":{"imageBased":{},"textBased":{},"textExtendedBadges":{"badgeObject":[{"attributes":{"description":"","fontColor":"#7E808C","iconId":"guiltfree/GF_Logo_android_3x","shortDescription":"options available"}}]}}},"aggregatedDiscountInfoV3":{"header":"ITEMS","subHeader":"AT ₹159"},"differentiatedUi":{"displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT","differentiatedUiMediaDetails":{"mediaType":"ADS_MEDIA_ENUM_IMAGE","lottie":{},"video":{}}},"reviewsSummary":{},"displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT","restaurantOfferPresentationInfo":{}},"analytics":{},"cta":{"link":"https://www.swiggy.com/restaurants/lunchbox-meals-and-thalis-rani-bhawan-nit-faridabad-242354","type":"WEBLINK"}},
]


const Body = () => {
    return(
        <div className="body">
          <div className="search">Search</div>
          <div className="res-container">
          {
            resList.map((restaurant) => (
                <RestaurantCard key = {restaurant.info.id} resData = {restaurant}/>
            ))
          }
          </div>
        </div>
    );
};

const AppLayout = () => {
    return (
        <div className="app">
            {/* Header */}
            <Header />
            {/* Body */}
            <Body/>
            {/* Footer */}
        </div>
    );
};
const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(<AppLayout/>)
